# Generated by Django 3.1.3 on 2020-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201214_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='especialista',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
