# Generated by Django 3.1.3 on 2020-12-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201214_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='especialista',
        ),
    ]
