# Generated by Django 3.0.7 on 2021-04-08 07:28

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auctions', '0021_auto_20210112_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='prazo',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='especialista',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='terminado',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='listing',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='NIF',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Tablets', 'Tablets'), ('Consolas', 'Consolas'), ('Bicicletas Motorizadas', 'Bicicletas Motorizadas'), ('Drones', 'Drones'), ('Fotografia e Video', 'Fotografia e Video'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='excerpt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
