# Generated by Django 3.0.7 on 2021-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_bid_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, null=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('Importante', 'Importante'), ('Não-Lida', 'Não-Lida'), ('Lida', 'Lida')], default='Não-Lida', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
