# Generated by Django 3.0.7 on 2021-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Importante', 'Importante'), ('Não-Lida', 'Não-Lida'), ('Lida', 'Lida')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='NIF',
            field=models.IntegerField(default=0),
        ),
    ]
