# Generated by Django 4.0.1 on 2022-02-20 13:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('auctions', '0026_auto_20210428_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='NIF',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Gadgets', 'Gadgets'), ('Consolas', 'Consolas'), ('Bicicletas Motorizadas', 'Bicicletas Motorizadas'), ('Drones', 'Drones'), ('Fotografia e Video', 'Fotografia e Video'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Gadgets', 'Gadgets'), ('Consolas', 'Consolas'), ('Bicicletas Motorizadas', 'Bicicletas Motorizadas'), ('Drones', 'Drones'), ('Fotografia e Video', 'Fotografia e Video'), ('Outros', 'Outros')], max_length=64)),
                ('title', models.CharField(max_length=30)),
                ('excerpt', models.CharField(max_length=100)),
                ('p1', models.TextField()),
                ('p2', models.TextField(blank=True, null=True)),
                ('p3', models.TextField(blank=True, null=True)),
                ('p4', models.TextField(blank=True, null=True)),
                ('p5', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ofertas/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ofertas/')),
                ('image3_link', models.CharField(blank=True, max_length=500, null=True)),
                ('image4_link', models.CharField(blank=True, max_length=500, null=True)),
                ('image5_link', models.CharField(blank=True, max_length=500, null=True)),
                ('image6_link', models.CharField(blank=True, max_length=500, null=True)),
                ('image7_link', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
