# Generated by Django 4.0.1 on 2022-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.AddField(
            model_name='news',
            name='image1_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image2_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image8_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image9_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Em atualização', 'Em atualização'), ('Fontes não verificadas', 'Fontes não verificadas'), ('Verificado', 'Verificado'), ('Fake News', 'Fake News')], default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Economia', 'Economia'), ('Politica', 'Politica'), ('Mundo', 'Mundo'), ('Desporto', 'Desporto'), ('Justiça', 'Justiça'), ('Lifestyle', 'Lifestyle'), ('Tecnologia', 'Tecnologia'), ('Ciência', 'Ciência')], max_length=64),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
