# Generated by Django 4.0.1 on 2022-04-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_news_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
