# Generated by Django 4.0.1 on 2022-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_rename_author_image_link_article_author_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Economia', 'Economia'), ('Politica', 'Politica'), ('Mundo', 'Mundo'), ('Desporto', 'Desporto'), ('Justiça', 'Justiça'), ('Lifestyle', 'Lifestyle'), ('Tecnologia', 'Tecnologia'), ('Ciência', 'Ciência'), ('Sociedade', 'Sociedade')], max_length=64),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
    ]
