from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("activelisting", views.activelisting, name="activelisting"),
    path("viewlisting/<int:product_id>", views.viewlisting, name="viewlisting"),
    path("like/<int:pk>", views.LikeView, name="like_post"),
    path("addtowatchlist/<int:product_id>",
         views.addtowatchlist, name="addtowatchlist"),
    path("addtoview/<int:product_id>",
         views.addtoview, name="addtoview"),
    path("invertidos", views.invertidos, name="invertidos"),
    path("artigo/<int:product_id>", views.artigo, name="artigo"),
    path("colocaroferta/<int:product_id>", views.colocaroferta, name="colocaroferta"),
    path("terminar/<int:product_id>", views.terminar, name="terminar"),
    path("addcomment/<int:product_id>", views.addcomment, name="addcomment"),
    path("closebid/<int:product_id>", views.closebid, name="closebid"),
    path("closedlisting", views.closedlisting, name="closedlisting"),
    path("resultados", views.search, name="resultados"),
    path("dresultados", views.searchDecrease, name="dresultados"),
    path("fresultados", views.searchFixed, name="fresultados"),
    path("aresultados", views.SearchAll, name="aresultados"),
    path("terminados", views.terminados, name="terminados"),
    path('anunciar', views.anunciar, name="anunciar"),
    path('criar', views.criar, name="criar"),
    path('contact', views.contact, name="contact"),
    path('closedbid/<int:product_id>"', views.closebid, name="closedbid"),
    path("smartphones", views.categ_smartphones, name="smartphones"),
    path("televisores", views.categ_televisores, name="televisores"),
    path("consolas", views.categ_consolas, name="consolas"),
    path("computadores", views.categ_computadores, name="computadores"),
    path("tablets", views.categ_tablets, name="tablets"),
    path("drones", views.categ_drones, name="drones"),
    path("outros", views.categ_outros, name="outros"),
    path("privacy", views.Privacy, name="privacy"),
    path('details/<slug:slug>/', views.vendas_detalhe, name="details"),
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('vencidos', views.vencidos, name="vencidos"),
    path('publicados', views.publicados, name='publicados'),
    path('watchlist', views.dwatchlist, name='watchlist'),
    path('viewlist', views.dviewlist, name='viewlist'),
    path('dhistorico', views.dhistorico, name='dhistorico'),
]
