# Generated by Django 3.1.3 on 2020-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201214_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='excerpt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem1',
            field=models.ImageField(default='no-img.jpg', upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem2',
            field=models.ImageField(blank=True, upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem3',
            field=models.ImageField(blank=True, upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem4',
            field=models.ImageField(blank=True, upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem5',
            field=models.ImageField(blank=True, upload_to='ofertas/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imagem6',
            field=models.ImageField(blank=True, upload_to='ofertas/'),
        ),
    ]
