# Generated by Django 3.1.3 on 2020-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='especialista',
            field=models.IntegerField(default=0),
        ),
    ]
