# Generated by Django 3.1.3 on 2020-12-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='especialista',
            field=models.IntegerField(blank=True),
        ),
    ]
