# Generated by Django 3.1.3 on 2020-12-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipping_cost',
            field=models.IntegerField(default=0),
        ),
    ]
