# Generated by Django 3.1.3 on 2021-01-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210112_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descritivo', models.TextField()),
                ('excerto', models.TextField()),
                ('pbase', models.IntegerField()),
                ('pmin', models.IntegerField()),
                ('imagem1', models.ImageField(default='no-img.jpg', upload_to='ofertas/')),
                ('imagem2', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem3', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem4', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem5', models.ImageField(blank=True, upload_to='ofertas/')),
                ('especialista', models.IntegerField(blank=True, default=0)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('terminado', models.BooleanField(default=False)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
