# Generated by Django 3.1.3 on 2021-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210122_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='oferta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
