# Generated by Django 3.1.3 on 2021-01-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210122_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='oferta',
        ),
        migrations.AddField(
            model_name='oferta',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
