# Generated by Django 3.1.3 on 2021-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210122_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
