# Generated by Django 3.1.3 on 2021-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_listing_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
