# Generated by Django 3.1.3 on 2021-01-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20210126_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverto',
            name='promovido',
            field=models.BooleanField(default=False),
        ),
    ]
