# Generated by Django 3.1.3 on 2021-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_inverto_promovido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverto',
            name='imagem1',
            field=models.ImageField(blank=True, default='no-img.jpg', upload_to='ofertas/'),
        ),
    ]
