# Generated by Django 3.1.3 on 2021-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20210126_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverto',
            name='seller',
        ),
        migrations.AddField(
            model_name='inverto',
            name='vendedor',
            field=models.CharField(default='Sem vendedor', max_length=300),
        ),
    ]
