# Generated by Django 3.1.3 on 2021-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20210129_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Tablets', 'Tablets'), ('Consolas', 'Consolas'), ('Televisões', 'Televisões'), ('Outros', 'Outros')], max_length=64, null=True),
        ),
    ]
