# Generated by Django 3.0.7 on 2021-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20210205_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=64)),
                ('vencedor', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('montante', models.IntegerField()),
                ('titulo', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
