# Generated by Django 3.0.7 on 2021-02-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_shopnow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopnow',
            old_name='starting_bid',
            new_name='price',
        ),
    ]
