# Generated by Django 3.0.7 on 2021-02-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20210210_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopnow',
            name='terminado',
        ),
        migrations.AddField(
            model_name='shopnow',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
