# Generated by Django 3.0.7 on 2021-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20210210_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopnow',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
