# Generated by Django 3.0.7 on 2021-02-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20210210_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopnow',
            name='publicado',
        ),
    ]
