# Generated by Django 3.0.7 on 2021-02-10 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_remove_shopnow_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopnow',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
