# Generated by Django 3.0.7 on 2021-02-12 11:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auctions', '0045_shopnow_publicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('pbase', models.IntegerField()),
                ('pmin', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Tablets', 'Tablets'), ('Consolas', 'Consolas'), ('Televisões', 'Televisões'), ('Outros', 'Outros')], max_length=64, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('imagem1', models.ImageField(blank=True, default='no-img.jpg', upload_to='ofertas/')),
                ('imagem2', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem3', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem4', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem5', models.ImageField(blank=True, upload_to='ofertas/')),
                ('expert', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Tablets', 'Tablets'), ('Consolas', 'Consolas'), ('Televisões', 'Televisões'), ('Outros', 'Outros')], max_length=64, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('imagem1', models.ImageField(default='no-img.jpg', upload_to='ofertas/')),
                ('imagem2', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem3', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem4', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem5', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem6', models.ImageField(blank=True, upload_to='ofertas/')),
                ('shipping_cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Increase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Computadores', 'Computadores'), ('Tablets', 'Tablets'), ('Consolas', 'Consolas'), ('Televisões', 'Televisões'), ('Outros', 'Outros')], max_length=64, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('imagem1', models.ImageField(default='no-img.jpg', upload_to='ofertas/')),
                ('imagem2', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem3', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem4', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem5', models.ImageField(blank=True, upload_to='ofertas/')),
                ('imagem6', models.ImageField(blank=True, upload_to='ofertas/')),
                ('expert', models.IntegerField(blank=True, default=0)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='Inverto',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ShopNow',
        ),
    ]
