# Generated by Django 3.0.7 on 2021-02-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20210212_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewlist',
            old_name='listingid',
            new_name='decreaseid',
        ),
    ]
