# Generated by Django 3.0.7 on 2021-03-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_auto_20210223_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='timestamp',
        ),
    ]
