# Generated by Django 3.0.7 on 2021-03-08 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_remove_oferta_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
