# Generated by Django 3.0.7 on 2021-03-15 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_auto_20210308_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='increase',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
